import type { JUSubscription } from './ju-sub-calendar';

export const MOCK_SUBSCRIPTIONS: JUSubscription[] = [
  {
    id: 'spotify',
    name: 'Spotify',
    logoUrl: 'https://cdn.simpleicons.org/spotify/1DB954',
    iconBg: '#1DB954',
    price: 9.99,
    billing: 'monthly',
    dayOfMonth: 4,
  },
  {
    id: 'notion',
    name: 'Notion',
    logoUrl: 'https://cdn.simpleicons.org/notion/000000',
    iconBg: '#ffffff',
    price: 15.99,
    billing: 'monthly',
    dayOfMonth: 4,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    logoUrl: 'https://cdn.simpleicons.org/perplexity/20808D',
    iconBg: '#1a1a2e',
    price: 16.99,
    billing: 'monthly',
    dayOfMonth: 4,
  },
  {
    id: 'figma',
    name: 'Figma',
    logoUrl: 'https://cdn.simpleicons.org/figma/F24E1E',
    iconBg: '#ffffff',
    price: 144.0,
    billing: 'yearly',
    dayOfMonth: 11,
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    logoUrl: 'https://cdn.simpleicons.org/github/ffffff',
    iconBg: '#24292f',
    price: 100.0,
    billing: 'yearly',
    dayOfMonth: 11,
  },
  {
    id: 'linear',
    name: 'Linear',
    logoUrl: 'https://cdn.simpleicons.org/linear/5E6AD2',
    iconBg: '#ffffff',
    price: 96.0,
    billing: 'yearly',
    dayOfMonth: 11,
  },
  {
    id: 'openai',
    name: 'ChatGPT Plus',
    logoUrl: 'https://cdn.simpleicons.org/openai/10a37f',
    iconBg: '#ffffff',
    price: 240.0,
    billing: 'yearly',
    dayOfMonth: 17,
  },
  {
    id: 'netflix',
    name: 'Netflix',
    logoUrl: 'https://cdn.simpleicons.org/netflix/E50914',
    iconBg: '#000000',
    price: 17.99,
    billing: 'monthly',
    dayOfMonth: 22,
  },
];
